version: '3.1'

services:

 db:
    image: mariadb:10.2
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_USER=crnotify
      - MYSQL_PASSWORD=CRNOTIFY_DB_PASS###
      - MYSQL_DATABASE=crnotifydb
    volumes:
      - ./mysql:/var/lib/mysql
    logging:
      options:
        max-size: "2m"
        max-file: "1"
    ports:
      - 1001:3306
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=0]