version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: "crnotify"
      MYSQL_PASS: "CRNOTIFY_DB_PASS_!!!"
      MYSQL_DATABASE: "crnotifydb"
    ports:
      - 1001:3306
    volumes:
      - ./mysql:/var/lib/mysql